# Generated by Django 6.0.7 on 2026-07-10 18:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('rules_summary', models.CharField(help_text="e.g. '11 vs 11, 2x45min halves'", max_length=255)),
                ('players_per_side', models.PositiveSmallIntegerField(default=11)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sub-Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('system_admin', 'System Admin'), ('county_ict', 'County ICT Officer'), ('sub_county_admin', 'Sub-County Admin'), ('ward_admin', 'Ward Admin')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='accounts.subcounty')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('verify', 'Verify'), ('generate_fixtures', 'Generate Fixtures'), ('promote', 'Promote Team'), ('login', 'Login')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, help_text='Snapshot of str(obj) at time of action', max_length=255)),
                ('changes', models.JSONField(blank=True, help_text="e.g. {'field': ['old', 'new']}", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline of the post', max_length=255)),
                ('tag', models.CharField(choices=[('announcement', 'Official Announcement'), ('match_report', 'Match Report'), ('fixture_update', 'Fixture Update'), ('general', 'General')], default='general', max_length=30)),
                ('body', models.TextField(help_text='The full story content')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to=settings.AUTH_USER_MODEL)),
                ('sub_county', models.ForeignKey(blank=True, help_text='Leave blank for County-Wide scope', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='accounts.subcounty')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, default='Anonymous Viewer', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.newspost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ward', 'Ward Phase'), ('sub_county', 'Sub-County Phase'), ('county', 'County Phase'), ('final', 'Final Phase')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases_created', to=settings.AUTH_USER_MODEL)),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='accounts.subcounty')),
            ],
            options={
                'ordering': ['tournament', 'order', 'ward__name', 'sub_county__name'],
            },
        ),
        migrations.CreateModel(
            name='PhaseSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_format', models.CharField(choices=[('league', 'League'), ('knockout', 'Knockout'), ('group_knockout', 'Group Stage + Knockout'), ('uefa_league_phase', 'UEFA-Style League Phase')], default='league', max_length=20)),
                ('legs', models.PositiveSmallIntegerField(default=1, help_text='1 = single round-robin, 2 = home & away')),
                ('fixtures_generated', models.BooleanField(default=False)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_sports', to='accounts.phase')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_entries', to='accounts.sport')),
            ],
            options={
                'verbose_name': 'Phase Sport',
                'verbose_name_plural': 'Phase Sports',
                'unique_together': {('phase', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phase_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.phasesport')),
            ],
            options={
                'unique_together': {('phase_sport', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(help_text='Matchday / round index')),
                ('leg', models.PositiveSmallIntegerField(default=1)),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('kickoff_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='accounts.group')),
                ('phase_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='accounts.phasesport')),
            ],
            options={
                'ordering': ['round_number', 'kickoff_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='accounts.fixture')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('home_ground', models.CharField(blank=True, max_length=150)),
                ('coach_name', models.CharField(blank=True, max_length=120)),
                ('coach_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_created', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='accounts.sport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='accounts.team'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('season', models.CharField(help_text="e.g. '2026'", max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_created', to=settings.AUTH_USER_MODEL)),
                ('sports', models.ManyToManyField(related_name='tournaments', to='accounts.sport')),
            ],
            options={
                'ordering': ['-season', 'name'],
                'unique_together': {('name', 'season')},
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='accounts.tournament'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='accounts.subcounty')),
            ],
            options={
                'verbose_name_plural': 'Wards',
                'ordering': ['sub_county__name', 'name'],
                'unique_together': {('sub_county', 'name')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='accounts.ward'),
        ),
        migrations.AddField(
            model_name='phase',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='accounts.ward'),
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='accounts.ward'),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('drawn', models.PositiveSmallIntegerField(default=0)),
                ('lost', models.PositiveSmallIntegerField(default=0)),
                ('goals_for', models.PositiveSmallIntegerField(default=0)),
                ('goals_against', models.PositiveSmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='accounts.group')),
                ('phase_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='accounts.phasesport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='accounts.team')),
            ],
            options={
                'ordering': ['-points', '-goals_for'],
                'unique_together': {('phase_sport', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PhaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.phase')),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='accounts.phaseentry')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_registered', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_entries', to='accounts.team')),
            ],
            options={
                'verbose_name_plural': 'Phase Entries',
                'unique_together': {('phase', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(blank=True, help_text="e.g. 'Midfielder', 'Setter'", max_length=60)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('yellow_card', models.IntegerField(default=0)),
                ('red_card', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_registered', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='accounts.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_players', to='accounts.tournament')),
            ],
            options={
                'ordering': ['team', 'jersey_number'],
                'unique_together': {('team', 'tournament', 'jersey_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'sport', 'ward')},
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('tournament', 'stage', 'ward', 'sub_county')},
        ),
    ]
