# Generated by Django 6.0.7 on 2026-07-13 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Link this news to a specific phase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='accounts.phase'),
        ),
    ]
