# Generated by Django 6.0.7 on 2026-07-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_player_assists_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tournament', to='accounts.subcounty'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tournament', to='accounts.ward'),
        ),
    ]
