# Generated by Django 6.0.7 on 2026-07-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tournament_sub_county_tournament_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('yellow', 'Yellow Card'), ('red', 'Red Card')], max_length=10)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_received', to='accounts.player')),
            ],
            options={
                'ordering': ['minute', 'created_at'],
            },
        ),
    ]
