# Generated by Django 6.0.7 on 2026-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_player_is_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('county_ict', 'County ICT Officer'), ('sub_county_admin', 'Sub-County Admin'), ('ward_admin', 'Ward Admin'), ('team_manager', 'Team Manager')], max_length=20),
        ),
    ]
